name: ${project.name}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
api-version: 1.13
authors:
- [EncryptSL, Steffion]
description: An easy to set up, Hide and seek plugin. Hide as blocks from the killer seekers.
softdepend: [LibsDisguises, ProtocolLib, Multiverse-Core, My Worlds, Vault]
load: POSTWORLD
commands:
  BlockHunt:
    usage: /<command>
    description: N/A
    aliases:
    - bh
    - prophunt
    - ph
    - hideandseek
    - has
    - hs
    - seekandfind
    - saf
    - sf